# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FkSN8jg3kdwWNvGEHvcXmkgzojBRuacV
"""

#import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#reading data
df=pd.read_csv("SampleSuperstore.csv")

"""**#1 UNDERSTANDING THE DATA**"""

df.head()

df.tail()

df.describe()

df.shape

df.columns

df.nunique()

df['Ship Mode'].unique()

df.info()

df.describe()

"""**#2 CLEANING THE DATA**"""

df.isnull().sum()
### #check for null values ,if there are null values remove it

df1=df.drop(['Postal Code'],axis=1)

df1.head()

"""## **#3 relationship analysis**"""

df.dtypes

"""#**OBSERVATION FROM PLOTS**"""

sns.pairplot(df, hue = 'Ship Mode')

df['Ship Mode'].value_counts()

sns.countplot(x=df['Ship Mode'])

df['Sub-Category'].value_counts()

plt.figure(figsize=(15,12))
df['Sub-Category'].value_counts().plot.pie(autopct='None')
plt.show()

"""##**Observation 1**
Maximum are from Binders, Paper, furnishings, Phones, storage, art, accessories and minimum from copiers, machines, suppliers
"""

df['State'].value_counts()

plt.figure(figsize=(15,12))
sns.countplot(x='State',data=df,palette='rocket_r',order=df['State'].value_counts().index)
plt.show()

"""##**Observation 2**
Highest number of buyers are from California and New York
"""

df.hist(figsize=(10,10),bins=50)
plt.show()

"""##**Observation 3**
Most customers tends to buy quantity of 2 and 3
Discount give maximum is 0 to 20 percent
"""

df.groupby('Region').sum()['Profit'].plot(kind='pie', autopct='%1.01f%%', explode=(0.025, 0.025, 0.025, 0.025))
plt.show()

fig,x=plt.subplots(figsize=(20,8))
x.scatter(df['Sales'],df['Profit'],color='green')
x.set_xlabel('Sales')
x.set_ylabel('Profit')
plt.show()

sns.lineplot(x='Discount',y='Profit',label='Profit',data=df)
plt.legend()
plt.show()

"""##**Observation 4**
No correlation between profit and discount
"""

df.groupby('Segment')[['Profit','Sales']].sum().plot.bar(color=['pink','blue'],figsize=(8,5))
plt.ylabel('Profit/Loss and sales')
plt.show()

"""##**Observation 5**
Profit and sales are maximum in consumer segment and minimum in Home Office segment
"""

plt.figure(figsize=(12,8))
plt.title('Segment wise Sales in each Region')
sns.barplot(x='Region',y='Sales',data=df,hue='Segment',order=df['Region'].value_counts().index,palette='rocket')
plt.xlabel('Region',fontsize=15)
plt.show()

"""##**Observation 6**
Segment wise sales are almost same in every region
"""

df.groupby('Region')[['Profit','Sales']].sum().plot.bar(color=['blue','red'],figsize=(8,5))
plt.ylabel('Profit/Loss and sales')
plt.show()

"""##**Observation 7**
Profit and sales are maximum in west region and minimum in south region





"""

ps = df.groupby('State')[['Sales','Profit']].sum().sort_values(by='Sales',ascending=False)
ps[:].plot.bar(color=['blue','orange'],figsize=(15,8))
plt.title('Profit/loss & Sales across states')
plt.xlabel('States')
plt.ylabel('Profit/loss & Sales')
plt.show()

t_states = df['State'].value_counts().nlargest(10)
t_states

df.groupby('Category')[['Profit','Sales']].sum().plot.bar(color=['yellow','purple'],alpha=0.9,figsize=(8,5))
plt.ylabel('Profit/Loss and sales')
plt.show()

ps = df.groupby('Sub-Category')[['Sales','Profit']].sum().sort_values(by='Sales',ascending=False)
ps[:].plot.bar(color=['red','lightblue'],figsize=(15,8))
plt.title('Profit/loss & Sales across states')
plt.xlabel('Sub-Category')
plt.ylabel('Profit/loss & Sales')
plt.show()

"""




##**Observation 8**
high profit is for california, new york
loss is for texas, pennsylvania, Ohio"""

