# -*- coding: utf-8 -*-
"""Score prediction[1.1].ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xDjqemnkUoefD3U4S2lmSJXjU7FiP_A8
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""**READING DATA**"""

data=pd.read_csv("http://bit.ly/w-data")
data.head(4)

data.shape

data.isnull==True

"""**PLOTTING DATA**"""

plt.xlabel('Hours',fontsize=15)
plt.ylabel('Scores',fontsize=15)
plt.scatter(data.Hours,data.Scores)
plt.show()

#to split into x and y axis
x=data.iloc[:,:-1].values
y=data.iloc[:,1].values

x

y

"""**SPLITTING**"""

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=0,test_size=0.2)

print("x_train shape=",x_train.shape)
print("x_test shape=",x_test.shape)
print("y_train shape=",y_train.shape)
print("y_test shape=",y_test.shape)

"""**TRAINING**"""

from sklearn.linear_model import LinearRegression
lr=LinearRegression()

lr.fit(x_train,y_train)

b0=lr.intercept_
b1=lr.coef_
print(b0,b1)

#plotting the line y0
y0=b0+b1*x_train
y0

plt.xlabel('Hours',fontsize=15)
plt.ylabel('Scores',fontsize=15)
plt.scatter(x_train,y_train,marker='X')
plt.plot(x_train,y0,color='orange')
plt.show()

y_pred=lr.predict(x_test)
y_pred

y_test

plt.xlabel('Hours',fontsize=15)
plt.ylabel('Scores',fontsize=15)
plt.scatter(x_test,y_test,marker='X')
plt.plot(x_test,y_pred,color='r')
plt.show()

"""**Comparison**"""

test=list(y_test)
pred=list(y_pred)
compare=pd.DataFrame({'Actual':test,'predicted':pred})
compare

"""**Accuracy**"""

from sklearn import metrics
metrics.r2_score(y_test,y_pred)

"""**Error prediction**"""

from sklearn.metrics import mean_squared_error,mean_absolute_error
mse=metrics.mean_squared_error(y_test,y_pred)
root=np.sqrt(metrics.mean_squared_error(y_test,y_pred))
abs_error=np.sqrt(metrics.mean_squared_error(y_test,y_pred))
print(mse,root,abs_error)

"""**prediction score**"""

prediction_score=lr.predict([[9.2]])
prediction_score